[package]
name = "docker-update-all"
version = "0.1.0"
authors = ["Mao Wtm <m@maowtm.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.66"
